### ISSUE TITLE
AutoLInk error

### ISSUE THREAD

**Issue by lxcom83** [pmprog/OpenXCOM.Tools#11]
With auto-connect enabled, once you select a unused LINK BOX and start scrolling with the mouse button to select it target link, A RED LINK line shows on the RMP window what linkable node is currently selected, before last build it only shows one red line at a time, Now as you scroll through each possible link option the red line shows the link then remove itself when you try the next one, however now it keep every previous link and adds another red line , the result can be lots of possible links showing on the screen.

**Comment by lxcom83** [comment]
These links are staying on the screen because ,when you scroll through possible return links, each one is being saved no matter how many you scroll through , you need to only save the reverse link when you select another object /Link etc

**Comment by pmprog** [comment]
Yeah, I didn't really realise you'd scroll, rather than dropping the list and selecting your node. That makes things much harder because the computer doesn't know when you're "finished" scrolling....

I have some ideas though

**Comment by pmprog** [comment]
Fixed. Will only create links when the combobox loses focus (ie, you go to do something else)
