### ISSUE TITLE
Creating LINKs between existing nodes with Mouse click on RMP window

### ISSUE THREAD

**Issue by lxcom83** [pmprog/OpenXCOM.Tools#14]
Normally when linking nodes, i select a LINK drop-down box and scroll through all possibility using the scroll wheel on my mouse ( this is how i found the auto link error) the graphical red line jumps around until i find my desired link. Can we add another feature that will allow me to do this by selecting the boxes on the screen instead of scrolling through all the options.

Example: 
 I select existing Node that i want to link from ( lets call this the Master node so you can follow me),
I activate reverse link tick box,
i select new box "Link via mouse" located above existing 5 link points,
I then select the secondary node i wish to link to my master node on the RMP window but instead of it switching focus away from my Master Node, it creates the link in both directions to this temporarily selected node, then i can select another node to link back to my master node. This is repeated until all NODES on Master node are full or someone unselected the Tick box.

**Comment by pmprog** [comment]
Once you have a node selected, rightclicking on another node will create a link. If you have "Autoconnect nodes" enabled, it will also try and create the reverse connection too
